# Generated by Django 4.2.27 on 2026-02-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_date',
            field=models.DateField(verbose_name='date chatted'),
        ),
    ]
